### ISSUE TITLE
api.searchItemsByName doesn't work

### ISSUE THREAD

**Issue by coderovich** [Xfaider48/node-csgotm-api#13]
Hello.

the method searchItemsByName does not work properly :( 

the example below always returns "internal error" from csgotm :
```
api.searchItemsByName([{'market_hash_name':"Tec-9 | Army Mesh (Well-Worn)"}]).then(trades => {
    console.log(trades);
}).catch(error => {
    console.log(error);
});
```

here in node-csgotm-api\lib\csgo_tm_api.js 
in  a simplified way the call 
`this.callPostMethodWithKey('MassSearchItemByName', { list: list }, gotOptions);`
 should post the "list" variable in another view. Like this for example:
```
var list = {};
items.forEach(function (item,i) {
   list["list["+i+"]"] = CSGOtmAPI.getItemHash(item);
});
return this.callPostMethodWithKey('MassSearchItemByName', list, gotOptions);
```

**Comment by malsatin** [comment]
Can you provide full error text?

**Comment by coderovich** [comment]
Sure.

Simple code to execute:
```javascript
let csgotm = require('node-csgotm-api');
let options = {'apiKey': 'API_KEY'};
let api = new csgotm.API(options);
api.searchItemsByName([{'market_hash_name': "Galil AR | Sage Spray (Battle-Scarred)"}]).then(offers => {
}).catch((err)=>{
    console.log(err);
});
```

the output is:
```javascript
$ > node test-api\index.js
{ Error: internal error
    at new CSGOtmAPIError (test-api\node_modules\node-csgotm-api\lib\csgo_tm_api.js:51:122)
    at test-api\node_modules\node-csgotm-api\lib\csgo_tm_api.js:1302:33
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'Error',
  requestedUrl: 'https://market.csgo.com/api/MassSearchItemByName/?key=API_KEY',
  response:
   PassThrough {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: false,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events:
      { end: [Function: onend],
        prefinish: [Function: prefinish],
        error: [Function: onerror],
        close: [Array],
        finish: [Function: onfinish] },
     _eventsCount: 5,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: true,
     _transformState:
      { afterTransform: [Function: bound afterTransform],
        needTransform: false,
        transforming: false,
        writecb: null,
        writechunk: null,
        writeencoding: 'buffer' },
     _flush: [Function: bound flush],
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'market.csgo.com',
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'market.csgo.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 359,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 17,
        [Symbol(bytesRead)]: 781 },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'market.csgo.com',
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'market.csgo.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 359,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 17,
        [Symbol(bytesRead)]: 781 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: false,
     headers:
      { date: 'Wed, 31 Oct 2018 10:39:16 GMT',
        'content-type': 'application/json; charset=UTF-8',
        'transfer-encoding': 'chunked',
        connection: 'close',
        'set-cookie': [Array],
        expires: 'Thu, 01 Jan 1970 00:00:01 GMT',
        'cache-control': 'no-cache',
        pragma: 'no-cache',
        'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
        server: 'cloudflare',
        'cf-ray': DME',
        'content-encoding': 'gzip' },
     rawHeaders:
      [ 'Date',
        'Wed, 31 Oct 2018 10:39:16 GMT',
        'Content-Type',
        'application/json; charset=UTF-8',
        'Transfer-Encoding',
        'chunked',
        'Connection',
        'close',
        'Set-Cookie',
        '__cfduid=; expires=Thu, 31-Oct-19 10:39:15 GMT; path=/; domain=.csgo.com; HttpOnly',
        'Expires',
        'Thu, 01 Jan 1970 00:00:01 GMT',
        'Cache-Control',
        'no-cache',
        'Pragma',
        'no-cache',
        'Set-Cookie',
        'PHPSESSIDAPI=; path=/',
        'set-cookie',
        '_identity=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; HttpOnly',
        'Expect-CT',
        'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
        'Server',
        'cloudflare',
        'CF-RAY',
        'DME',
        'Content-Encoding',
        'gzip' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: 'https://market.csgo.com/api/MassSearchItemByName/?key=API_KEY',
     method: null,
     statusCode: 200,
     statusMessage: 'OK',
     client:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'market.csgo.com',
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'market.csgo.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 359,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 17,
        [Symbol(bytesRead)]: 781 },
     _consuming: false,
     _dumped: false,
     req:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 49,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /api/MassSearchItemByName/?key=API_KEY HTTP/1.1\r\nuser-agent: got/9.3.0 (https://github.com/sindresorhus/got)\r\naccept: application/json\r\naccept-encoding: gzip, deflate\r\ncontent-type: application/x-www-form-u
rlencoded\r\ncontent-length: 49\r\nHost: market.csgo.com\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/api/MassSearchItemByName/?key=API_KEY',
        _ended: true,
        res: [Object],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        emit: [Function],
        [Symbol(outHeadersKey)]: [Object] },
     requestUrl: 'https://market.csgo.com/api/MassSearchItemByName/?key=API_KEY',
     retryCount: 0,
     timings:
      { start: 1540982354419,
        socket: 1540982354423,
        lookup: 1540982354423,
        connect: 1540982354435,
        upload: 1540982354485,
        response: 1540982354582,
        end: 1540982354585,
        error: null,
        phases: [Object] },
     redirectUrls: [],
     setTimeout: [Function: bound bound setTimeout],
     body: { success: false, error: 'internal error' } },
  gotOptions:
   { form: true,
     body: { list: [Array] },
     json: true,
     headers: {},
     hooks:
      { beforeRequest: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: [] },
     retry: { retries: 2, methods: [Object], statusCodes: [Object] } } }
```

**Comment by coderovich** [comment]
thx )
